version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    restart: always
    volumes:
      - ./docker_data/db_django:/var/lib/mysql

  # TODO: Пароль к redis
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    env_file:
      - .env
    restart: always
    volumes:
      - ./docker_data/redis_data:/var/lib/redis