# Generated by Django 4.2.4 on 2023-08-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=300)),
                ("price", models.IntegerField()),
                ("discounted_price", models.IntegerField()),
                ("discount", models.IntegerField()),
                ("rating", models.FloatField()),
                ("comments_amount", models.IntegerField()),
                ("delivery_date", models.CharField(max_length=30)),
                ("tag", models.CharField(max_length=150)),
                ("url", models.TextField(max_length=1000)),
            ],
        ),
    ]
