# Generated by Django 3.1.14 on 2023-08-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=300)),
                ("price", models.IntegerField()),
                ("discounted_price", models.IntegerField()),
                ("rating", models.FloatField()),
                ("comments_amount", models.IntegerField()),
                ("delivery_date", models.CharField(max_length=30)),
                ("tag", models.CharField(max_length=150)),
                ("url", models.URLField()),
            ],
        ),
    ]
