# Generated by Django 3.1.14 on 2023-08-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
